export const FETCH_COMMODITY_SETS = 'FETCH_COMMODITY_SETS'
export const FETCH_COMMODITY_SETS_FAIL = 'FETCH_COMMODITY_SETS_FAIL'
export const FETCH_COMMODITY_SETS_SUCCESS = 'FETCH_COMMODITY_SETS_SUCCESS'
