export const CREATE_SESSION = 'CREATE_SESSION'
export const CREATE_SESSION_FAIL = 'CREATE_SESSION_FAIL'
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS'
export const RESET_STATE = 'RESET_STATE'
