export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const EDIT_SIGNUP_FIELD = 'EDIT_SIGNUP_FIELD'
